defaults: &defaults
  adapter: mysql2
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] || 'root' %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: <%= ENV['GH_MYSQL_SOCKET'] %>

development:
  <<: *defaults
  database: theoj_development

test:
  <<: *defaults
  database: theoj_test

production:
  <<: *defaults
  database: theoj_production

